# locust.conf

# Which locustfile to use
locustfile = locustfile.py


# Backend base URL
host = https://api-cycle-dev.azurewebsites.net

# Web UI settings
web-host = 127.0.0.1
web-port = 8090

; # Default values when running in headless mode (optional)
; users = 10
; spawn-rate = 2

loglevel = INFO
