
# Which locustfile to use
; locustfile = weeks/week1_2_basics.py
; locustfile = weeks/week3_4_modular.py
locustfile = weeks/week5_6_shapes.py
; locustfile = weeks/week7_8_scaling_ci.py






# Backend base URL
host = https://api-cycle-dev.azurewebsites.net

# Web UI settings
web-host = 127.0.0.1
web-port = 8090

; # Default values when running in headless mode (optional)
; users = 10
; spawn-rate = 2

loglevel = INFO
